Corrected virtual_mrna_list format in 155 to be consistent with line 157. Tried to correct computation of block start, same
TypeError: string indicies must be integers, not str

Still need to print a line for each mRNA.